wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      Images_wandb_delimeter_predictions:
        key: Images_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': latte_st
          '1': tomato_juice
          '10': bubbletea_blacksugar
          '11': cappuccino
          '12': caramel_macchiato
          '13': grape_juice
          '14': mango_juice
          '15': latte_caffe
          '16': shake_choco
          '17': unknown
          '2': latte_goguma
          '3': americano
          '4': latte_greentea
          '5': latte_vanilla
          '6': caffe_mocha
          '7': frappuccino_greentea
          '8': hongsi_juice
          '9': frappuccino_javachip
    cli_version: 0.10.26
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.8.5
      5: 0.10.26
      8:
      - 3
      - 5
adam:
  desc: null
  value: false
batch_size:
  desc: null
  value: 12
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
cfg:
  desc: null
  value: ''
data:
  desc: null
  value: .\data\custom.yaml
device:
  desc: null
  value: ''
epochs:
  desc: null
  value: 80
evolve:
  desc: null
  value: false
exist_ok:
  desc: null
  value: false
global_rank:
  desc: null
  value: -1
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.00046875
image_weights:
  desc: null
  value: false
img_size:
  desc: null
  value:
  - 384
  - 384
local_rank:
  desc: null
  value: -1
log_artifacts:
  desc: null
  value: false
log_imgs:
  desc: null
  value: 16
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
project:
  desc: null
  value: runs/train
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs\train\exp15
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
total_batch_size:
  desc: null
  value: 12
weights:
  desc: null
  value: yolov5x.pt
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: 1
